spring:
  output:
    ansi:
      enabled: ALWAYS
  devtools:
    restart:
      enabled: false
  datasource:
    url: jdbc:h2:mem:test;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    open-in-view: false
  h2:
    console:
      enabled: true
logging:
  level:
    root: WARN
    com.monkeydp: DEBUG
dms:
  root-dir: ${rootDir}
  module:
    dm-parent-dir: \${dms.root-dir}/dm
    modules-dir: \${dms.root-dir}/ignore/modules